global:
  message: Welcome to customer service prod environment!!
server:
  port: 8083
message: Hello from Prod!
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/cust_prod
     username: root
     password: 814362
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
